[build]
  publish = "."
  functions = "netlify/functions"
  command = ""

[[headers]]
  for = "/*.html"
  [headers.values]
    Cache-Control = "no-cache, no-store, must-revalidate"
    Pragma = "no-cache"
    Expires = "0"

[[redirects]]
  from = "/api/data"
  to = "/.netlify/functions/data"
  status = 200
